### ISSUE TITLE
Segmentation fault using WSL and VcXsrv (also a missing folder error)

### ISSUE THREAD

**Issue by HyperCodec** [mate-desktop/mate-desktop#549]
#### Expected behavior
It should export the desktop to 

#### Actual behavior
Crashes with ` couldn't access control socket: /mnt/wslg/runtime-dir/keyring/control: No such file or directory` and a segmentation fault
![image](https://user-images.githubusercontent.com/72839119/227796260-23a022f4-466f-4987-9746-e74a24ce350f.png)

Running on the normal Debian terminal rather than using the `Debian` command (apparently they aren't the same executable?) gives this error for whatever reason:
![image](https://user-images.githubusercontent.com/72839119/227796613-e5975dfd-aed0-465c-84d3-c46134346cbd.png)
(the second error still segmentation faults after `/tmp/.ICE-unix` is owned by root)

#### Steps to reproduce the behavior
```yaml
step 1: 
  install Debian Linux subsystem:
    - PowerShell as administrator: "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux" | go to "turn windows future on or off"
    - Microsoft Store: install "Debian"

step 2: 
  install mate desktop on Debian:
    - open Debian
    - sudo apt-get update
    - sudo apt install task-mate-desktop
    
step 3: 
    - open XLauch (VcXsrv)
      - select: "One large window"
      - Display number: 0
      - next
      - Start no client
      - next 
      - finish

step 4: 
  setup display: 
    - export DISPLAY=:0
    - export LIBGL_ALWAYS_INDIRECT=1

step 5: 
  start Mate-desktop environment: 
    - mate-session
``` 

#### MATE general version
1.26.1 (or whatever is the latest stable release as of 3/26/2023)

#### Package version
![image](https://user-images.githubusercontent.com/72839119/227796886-0ddb3bba-a738-4ba3-bbc7-92d06f5ede09.png)

#### Linux Distribution
![image](https://user-images.githubusercontent.com/72839119/227797132-61ddd2de-5843-4a20-b0a3-2d8c35aaf49e.png)

#### Link to bugreport of your Distribution (requirement)
?
